# Generated by Django 3.0.6 on 2020-06-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='books',
            field=models.ManyToManyField(default=None, related_name='bookshelves', to='oak.Book'),
        ),
    ]
